# SD212: Graph Learning

# Sparse Matrices

In this lab, you will learn to use sparse matrices.

In [89]:
import numpy as np
from scipy import sparse

## CSR format

We first focus on the [CSR](https://docs.scipy.org/doc/scipy/reference/generated/scipy.sparse.csr_matrix.html)  (Compressed Sparse Row) format. Note that there is the [CSC](https://docs.scipy.org/doc/scipy/reference/generated/scipy.sparse.csc_matrix.html) (Compressed Sparse Column) format, which is nothing but the CSR format of the transpose matrix.

In [90]:
# random matrix (dense format)
X_dense = np.random.randint(3, size = (10,5))

In [91]:
X_dense

array([[0, 1, 0, 2, 1],
       [1, 2, 2, 1, 1],
       [1, 1, 1, 2, 0],
       [0, 0, 1, 2, 0],
       [2, 0, 1, 1, 1],
       [0, 2, 2, 0, 2],
       [0, 1, 0, 1, 1],
       [0, 1, 1, 1, 1],
       [0, 2, 2, 1, 1],
       [0, 2, 2, 0, 1]])

In [92]:
X_csr = sparse.csr_matrix(X_dense)

In [93]:
X_csr.shape

(10, 5)

In [94]:
# number of non-zeros
X_csr.nnz

35

The data structure consists of 3 vectors:

In [95]:
X_csr.indices

array([1, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 2, 3, 0, 2, 3, 4, 1, 2, 4, 1,
       3, 4, 1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 4])

In [96]:
X_csr.indptr

array([ 0,  3,  8, 12, 14, 18, 21, 24, 28, 32, 35])

In [97]:
X_csr.data

array([1, 2, 1, 1, 2, 2, 1, 1, 1, 1, 1, 2, 1, 2, 2, 1, 1, 1, 2, 2, 2, 1,
       1, 1, 1, 1, 1, 1, 2, 2, 1, 1, 2, 2, 1])

## To do

* Can you find the number of non-zeros from these 3 vectors?
* What about the shape of the matrix?

The number of non-zeros of the matrix is `len(X_csr.data)`.  
The shape of the matrix is `(len(X_csr.indptr) - 1, max(X_csr.indices) + 1)` (if the last column contains at least one non-zero).

In [99]:
print(f"{len(X_csr.data) == X_csr.nnz}")
print(f"{(len(X_csr.indptr) - 1, max(X_csr.indices) + 1) == X_csr.shape}")

True
True


## Arithmetic

Usual arithmetic operations apply to sparse matrices. The only contraint is to have the sparse matrix on the left-hand side of the operator.

In [12]:
n_row, n_col = 10, 4
X_dense = np.random.randint(2, size = (n_row, n_col))
X = sparse.csr_matrix(X_dense)

In [13]:
X_dense

array([[1, 0, 1, 0],
       [0, 0, 0, 1],
       [1, 1, 1, 1],
       [0, 1, 1, 0],
       [1, 1, 0, 0],
       [0, 1, 1, 0],
       [0, 0, 1, 0],
       [0, 1, 0, 1],
       [0, 1, 0, 1],
       [0, 1, 0, 0]])

In [14]:
a = np.ones(n_col, dtype=int)

In [15]:
b = X.dot(a)

In [16]:
b

array([2, 1, 4, 2, 2, 2, 1, 2, 2, 1], dtype=int32)

In [17]:
a = np.ones(n_row, dtype=int)
b = X.T.dot(a)

In [18]:
b

array([3, 7, 5, 4], dtype=int32)

In [19]:
A = np.random.randint(2, size=(n_col, 2))
B = X.dot(A)

In [20]:
A

array([[1, 0],
       [1, 0],
       [0, 1],
       [1, 1]])

In [21]:
B

array([[1, 1],
       [1, 1],
       [3, 2],
       [1, 1],
       [2, 0],
       [1, 1],
       [0, 1],
       [2, 1],
       [2, 1],
       [1, 0]], dtype=int32)

In [22]:
A = sparse.csr_matrix(A)
B = X.dot(A)

In [23]:
B

<10x2 sparse matrix of type '<class 'numpy.intc'>'
	with 17 stored elements in Compressed Sparse Row format>

In [24]:
B.toarray()

array([[1, 1],
       [1, 1],
       [3, 2],
       [1, 1],
       [2, 0],
       [1, 1],
       [0, 1],
       [2, 1],
       [2, 1],
       [1, 0]], dtype=int32)

In [25]:
X.T.dot(X)

<4x4 sparse matrix of type '<class 'numpy.intc'>'
	with 16 stored elements in Compressed Sparse Column format>

In [26]:
X.dot(X.T)

<10x10 sparse matrix of type '<class 'numpy.intc'>'
	with 74 stored elements in Compressed Sparse Row format>

In [27]:
n_row, n_col = 10, 5
X_dense = np.random.randint(3, size = (n_row, n_col))
X = sparse.csr_matrix(X_dense)

In [28]:
X

<10x5 sparse matrix of type '<class 'numpy.int32'>'
	with 31 stored elements in Compressed Sparse Row format>

In [29]:
Y = X > 1

In [30]:
Y

<10x5 sparse matrix of type '<class 'numpy.bool_'>'
	with 15 stored elements in Compressed Sparse Row format>

In [31]:
Y.dot(np.ones(n_col, dtype=int))

array([2, 1, 2, 2, 2, 3, 0, 1, 1, 1], dtype=int32)

In [32]:
Y.dot(np.ones(n_col, dtype=bool))

array([ True,  True,  True,  True,  True,  True, False,  True,  True,
        True])

In [33]:
Z = 2 * X + 5 * Y

In [34]:
Z

<10x5 sparse matrix of type '<class 'numpy.intc'>'
	with 31 stored elements in Compressed Sparse Row format>

In [35]:
Z.power(2)

<10x5 sparse matrix of type '<class 'numpy.intc'>'
	with 31 stored elements in Compressed Sparse Row format>

## To do

Consider the following matrix:

In [36]:
n_row, n_col = 20, 4
X = sparse.csr_matrix(np.random.randint(3, size = (n_row, n_col)))

* Compute the vector of the Euclidean norm of each row.

In [37]:
X_square = X.copy()
X_square.data = X_square.data ** 2
np.sqrt(X_square.dot(np.ones(X_square.shape[1])))

array([3.60555128, 2.44948974, 2.44948974, 2.82842712, 2.23606798,
       2.23606798, 2.82842712, 3.        , 3.        , 2.44948974,
       3.        , 3.16227766, 3.46410162, 2.23606798, 1.73205081,
       2.82842712, 2.44948974, 2.82842712, 2.        , 3.        ])

## Slicing

Sparse matrices can be sliced like numpy arrays.

In [38]:
n_row, n_col = 10, 5
X_dense = np.random.randint(3, size = (n_row, n_col))

In [39]:
X = sparse.csr_matrix(X_dense)

In [40]:
indices = [2, 5, 6]

In [41]:
X[indices]

<3x5 sparse matrix of type '<class 'numpy.int32'>'
	with 10 stored elements in Compressed Sparse Row format>

In [42]:
X[:, [1, 3]]

<10x2 sparse matrix of type '<class 'numpy.int32'>'
	with 12 stored elements in Compressed Sparse Row format>

## To do 

Consider the following matrix:

In [43]:
n_row, n_col = 20, 10
X = sparse.csr_matrix(np.random.randint(3, size = (n_row, n_col)))

* Select the 5 rows of largest sums and build the corresponding CSR matrix (size 5 x 10).

In [44]:
sum_rows = X.dot(np.ones(X.shape[1]))
sorted_indexes = np.argsort(sum_rows)[-5:]
X_new = X[sorted_indexes, :].copy()
print(f"Shape: {X_new.shape}")
print(f"Indices: {X_new.indices}")
print(f"Data: {X_new.data}")
print(f"Indptr: {X_new.indptr}")

Shape: (5, 10)
Indices: [1 2 3 4 5 6 7 8 1 2 3 4 5 8 9 0 1 3 4 6 7 8 9 0 1 3 4 5 6 7 9 0 1 2 3 4 5
 7 8 9]
Data: [1 2 1 1 1 2 2 1 1 2 1 1 2 2 2 1 2 2 1 2 1 1 1 2 1 2 2 2 2 1 1 1 2 2 2 1 2
 2 2 1]
Indptr: [ 0  8 15 23 31 40]


## DIAG format

In [45]:
D = sparse.diags(np.arange(10))

In [46]:
D

<10x10 sparse matrix of type '<class 'numpy.float64'>'
	with 10 stored elements (1 diagonals) in DIAgonal format>

In [47]:
D.data

array([[0., 1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [48]:
D.nnz

10

In [49]:
D = sparse.csr_matrix(D)

In [50]:
D.data

array([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [51]:
D.nnz

9

In [52]:
n_row, n_col = 10, 4
X = sparse.csr_matrix(np.random.randint(2, size = (n_row, n_col)))

In [53]:
D.dot(X)

<10x4 sparse matrix of type '<class 'numpy.float64'>'
	with 19 stored elements in Compressed Sparse Row format>

In [54]:
D = sparse.diags(np.ones(4))

In [55]:
X.dot(D)

<10x4 sparse matrix of type '<class 'numpy.float64'>'
	with 21 stored elements in Compressed Sparse Row format>

## To do

Consider the following matrix:

In [56]:
n_row, n_col = 20, 4
X = sparse.csr_matrix(np.random.randint(2, size = (n_row, n_col)))

Using sparse diagonal matrices:
* Normalize this matrix so that each row sums to 1 (or to 0 if the whole row is zero). 

## COO format

Another way to represent sparse matrices is the COO (COOrdinate) format. It is useful to load a matrix from a list of entries.

In [57]:
row = [1, 4, 2]
col = [2, 0, 2]
data = [1, 2, 3]

In [58]:
X_coo = sparse.coo_matrix((data, (row, col)), shape=(5, 5))

In [59]:
X_coo

<5x5 sparse matrix of type '<class 'numpy.int32'>'
	with 3 stored elements in COOrdinate format>

In [60]:
X_coo.row

array([1, 4, 2])

In [61]:
X_coo.col

array([2, 0, 2])

In [62]:
X_coo.data

array([1, 2, 3])

You can change the format:

In [63]:
X_csr = X_coo.tocsr()

In [64]:
X_csr

<5x5 sparse matrix of type '<class 'numpy.int32'>'
	with 3 stored elements in Compressed Sparse Row format>

In [65]:
X_csr.indices

array([2, 2, 0])

In [66]:
X_csr.indptr

array([0, 0, 1, 2, 2, 3])

In [67]:
X_csr.data

array([1, 3, 2])

In [68]:
X_csr.tocoo()

<5x5 sparse matrix of type '<class 'numpy.int32'>'
	with 3 stored elements in COOrdinate format>

You can directly load a CSR matrix from COO format:

In [69]:
X_csr = sparse.csr_matrix((data, (row, col)), shape=(5, 5))

In [70]:
X_csr

<5x5 sparse matrix of type '<class 'numpy.int32'>'
	with 3 stored elements in Compressed Sparse Row format>

Duplicate entries are not summed by default in the COO format (also in the CSR format in the last version of Scipy):

In [71]:
row = [1, 4, 2, 1]
col = [2, 0, 2, 2]
data = [1, 2, 3, 4]

In [72]:
X_coo = sparse.coo_matrix((data, (row, col)), shape=(5, 5))

In [73]:
X_coo

<5x5 sparse matrix of type '<class 'numpy.int32'>'
	with 4 stored elements in COOrdinate format>

In [74]:
X_coo.nnz

4

In [75]:
X_coo.toarray()

array([[0, 0, 0, 0, 0],
       [0, 0, 5, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 0, 0],
       [2, 0, 0, 0, 0]])

In [76]:
X_coo.dot(np.ones(5, dtype=int))

array([0, 5, 3, 0, 2], dtype=int32)

In [77]:
X_coo.data

array([1, 2, 3, 4])

In [78]:
X_coo.sum_duplicates()

In [79]:
X_coo

<5x5 sparse matrix of type '<class 'numpy.int32'>'
	with 3 stored elements in COOrdinate format>

In [80]:
X_coo.data

array([5, 3, 2])

If data contain some zeros, these are coded as non-zeros by default:

In [81]:
row = [1, 4, 2]
col = [2, 0, 2]
data = [1, 2, 0]

In [82]:
X_csr = sparse.csr_matrix((data, (row, col)), shape=(5, 5))

In [83]:
X_csr

<5x5 sparse matrix of type '<class 'numpy.int32'>'
	with 3 stored elements in Compressed Sparse Row format>

In [84]:
X_csr.eliminate_zeros()

In [85]:
X_csr

<5x5 sparse matrix of type '<class 'numpy.int32'>'
	with 2 stored elements in Compressed Sparse Row format>

## To do

Consider the following matrix:

In [86]:
row = [1, 1, 2, 4, 2, 1]
col = [2, 2, 2, 0, 2, 2]
data = [1, 2, 3, 4, 0, 2]

X_csr = sparse.csr_matrix((data, (row, col)), shape=(5, 5))
X_csr.sum_duplicates()

* What is the number of non-zeros? 
* Check your answer using ``nnz``.

The number of non-zeros is ``.

In [87]:
X_csr.nnz == 

SyntaxError: invalid syntax (453253602.py, line 1)